# v3 scripts (draft for the owner's approval). Tags: HOOK, YOU (why it matters to you), CTX (context/term first),
# STEP, SIGN (signpost), NEXT (what happens next / what you can do), ASK (comment question).
V3 = {
 "plague_story": [
  ("HOOK", "Doctors suspect the plague killed a lab worker in Siberia."),
  ("CTX",  "The plague is the same disease that caused the Black Death in the fourteenth century."),
  ("YOU",  "And it matters to Americans too."),
  ("STEP", "The worker was a twenty-eight-year-old technician at a lab in Irkutsk, Russia, that studies the plague."),
  ("STEP", "She went to hospital on September twenty-ninth and died a few days later."),
  ("STEP", "Officials isolated [one hundred ninety-seven|197] people who may have had contact with her."),
  ("STEP", "But the plague has not been confirmed."),
  ("STEP", "Russia's health agency says she died of pneumonia with an unknown cause."),
  ("SIGN", "Now, here is why it matters to Americans."),
  ("STEP", "The plague still infects about seven people in the United States every year, mostly in the West."),
  ("STEP", "People usually catch it from the bite of a flea that lived on a wild animal, like a squirrel or a prairie dog."),
  ("STEP", "The good news is that antibiotics can treat it when it is caught early."),
  ("NEXT", "So if you fall sick after contact with wild animals in the West, see a doctor quickly."),
  ("ASK",  "Did you know the plague still exists in America?"),
 ],
 "jobs_story": [
  ("HOOK", "America added only twenty-nine thousand jobs in September."),
  ("STEP", "Economists expected about ninety thousand, so the official number was less than a third of that."),
  ("YOU",  "If you are looking for work, this matters to you."),
  ("STEP", "The unemployment rate also rose, from four point one to four point two percent."),
  ("CTX",  "That means about four in every hundred people in the workforce are out of work and looking for a job."),
  ("SIGN", "Pay is growing slowly too."),
  ("STEP", "Average hourly pay rose three percent over the past year, the slowest rise since twenty twenty-one."),
  ("SIGN", "So where are the new jobs?"),
  ("STEP", "Most of them were in health care, with a few more in construction and in factories."),
  ("STEP", "Economists call this a low hire, low fire job market."),
  ("STEP", "Companies are not laying many people off, but they are not hiring many people either."),
  ("NEXT", "The next jobs report comes out on November sixth, and we will tell you what it shows."),
  ("ASK",  "Is it harder to find a job where you live?"),
 ],
 "japan_story": [
  ("HOOK", "Japan just made staying in the country for good twenty times more expensive."),
  ("STEP", "On October first, the fee for permanent residency jumped from [ten thousand|10,000] yen to [two hundred thousand|200,000] yen."),
  ("CTX",  "That is a jump from about sixty-three dollars to about twelve hundred and seventy dollars."),
  ("YOU",  "So if you ever dreamed of moving to Japan, here is what you need to know."),
  ("CTX",  "Permanent residency lets a foreigner stay in Japan with no time limit."),
  ("STEP", "But it does not make them a citizen, and it does not come with a Japanese passport."),
  ("STEP", "Japan now has more than four million foreign residents, which is a record."),
  ("SIGN", "So why did Japan raise the fee so much?"),
  ("STEP", "The government says the new fee covers the real cost of handling applications."),
  ("STEP", "It also says the fee is now closer to what other countries charge."),
  ("SIGN", "And there is one more change."),
  ("STEP", "Applicants now also need a higher income to qualify."),
  ("ASK",  "Would you pay twelve hundred dollars to live in Japan for good?"),
 ],
 "diesel_story": [
  ("HOOK", "Diesel just hit its highest price ever in the United States."),
  ("STEP", "On September twenty-second, the average gallon cost six dollars and fifty-two cents."),
  ("YOU",  "Even if you never buy diesel, you are probably paying for it."),
  ("STEP", "The trucks that bring food and goods to your stores run on diesel."),
  ("STEP", "So when diesel costs more, almost everything in the store can cost more too."),
  ("SIGN", "Why did the price jump so much?"),
  ("STEP", "The war with Iran has stopped most oil tankers from passing through the Strait of Hormuz."),
  ("CTX",  "That narrow sea route normally carries about one in every five barrels of oil the world uses."),
  ("STEP", "With less oil getting through, diesel became scarce all around the world."),
  ("STEP", "On October second, the G7, a group of seven of the world's biggest economies, agreed on a plan."),
  ("STEP", "Together, they will release up to one hundred million barrels of oil and diesel from their emergency reserves."),
  ("STEP", "Energy experts say diesel could fall by about twenty-five cents a gallon within a few weeks."),
  ("SIGN", "But there is a catch."),
  ("STEP", "Emergency reserves are a short-term fix, and they will have to be refilled later."),
  ("NEXT", "So prices may drop soon, but they may not stay low for long."),
  ("ASK",  "Have you noticed higher prices at the store?"),
 ],
 "apple_story": [
  ("HOOK", "If you use a Mac, Apple is changing a setting that lets apps see your private files."),
  ("CTX",  "The setting is called Full Disk Access."),
  ("STEP", "When you turn it on for an app, that app can see almost everything on your Mac."),
  ("STEP", "That includes your files, your emails, your messages and even your browsing history."),
  ("STEP", "Many new AI helpers ask for this access, so they can work for you in the background."),
  ("STEP", "On October second, Apple warned app makers that this could expose everything on your computer without your full knowledge and understanding."),
  ("STEP", "So Apple plans to make this setting harder to turn on."),
  ("STEP", "You will need to take a very clear and deliberate step before an app gets that access."),
  ("STEP", "Apple has not said when this change will arrive."),
  ("NEXT", "Until then, you can see which apps already have it in System Settings, under Privacy and Security."),
  ("ASK",  "Would you let an AI read everything on your computer?"),
 ],
 "tesla_story": [
  ("HOOK", "Tesla's taxi with no steering wheel just finished its first paid month."),
  ("CTX",  "It is called the Cybercab, and it carries passengers around Austin, Texas, with no driver."),
  ("CTX",  "It has no pedals either, so nobody inside can take control."),
  ("SIGN", "It was a bumpy start."),
  ("STEP", "Passengers complained about long waits and about cars picking them up in the wrong spots."),
  ("STEP", "Some also had problems with the doors and the trunk."),
  ("STEP", "So far, no major crashes have been reported."),
  ("STEP", "But federal safety regulators have opened a review of the car."),
  ("STEP", "Austin firefighters have also asked for clear rules on how to handle a car with no driver controls."),
  ("SIGN", "Even so, Tesla is not slowing down."),
  ("STEP", "The number of Cybercabs registered in Texas has grown from forty-five at launch to one hundred sixty-nine."),
  ("CTX",  "That is almost four times as many."),
  ("STEP", "Elon Musk says the company is being extremely careful with safety."),
  ("ASK",  "Would you ride in a car with no steering wheel?"),
 ],
}
